CREATE TABLE care_record (id uuid PRIMARY KEY,church_id uuid NOT NULL,member_id uuid,household_id uuid,assignee_id uuid NOT NULL,kind text NOT NULL CHECK(kind IN ('VISIT','CALL','MESSAGE','MEETING')),occurred_at timestamptz NOT NULL,follow_up_on date,completed_at timestamptz,version integer NOT NULL DEFAULT 1,UNIQUE(church_id,id),CHECK((member_id IS NULL)<>(household_id IS NULL)),FOREIGN KEY(church_id,member_id) REFERENCES member(church_id,id),FOREIGN KEY(church_id,household_id) REFERENCES household(church_id,id),FOREIGN KEY(church_id,assignee_id) REFERENCES app_user(church_id,id));
CREATE TABLE care_change (id uuid PRIMARY KEY,church_id uuid NOT NULL,record_id uuid NOT NULL,assignee_id uuid NOT NULL,follow_up_on date,completed_at timestamptz,actor_id uuid NOT NULL,version integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(record_id,version),FOREIGN KEY(church_id,record_id) REFERENCES care_record(church_id,id),FOREIGN KEY(church_id,assignee_id) REFERENCES app_user(church_id,id),FOREIGN KEY(church_id,actor_id) REFERENCES app_user(church_id,id));
CREATE TRIGGER care_history_immutable BEFORE UPDATE OR DELETE ON care_change FOR EACH ROW EXECUTE FUNCTION prevent_operation_history_change();
CREATE TABLE care_policy (church_id uuid PRIMARY KEY REFERENCES church(id),enabled boolean NOT NULL DEFAULT false,retention_days integer NOT NULL CHECK(retention_days BETWEEN 1 AND 3650),reference text NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE care_note (id uuid PRIMARY KEY,church_id uuid NOT NULL,record_id uuid NOT NULL,author_id uuid NOT NULL,visibility text NOT NULL CHECK(visibility IN ('ASSIGNEE','ROLE')),role_id uuid,ciphertext text,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),purged_at timestamptz,CHECK((visibility='ROLE')=(role_id IS NOT NULL)),FOREIGN KEY(church_id,record_id) REFERENCES care_record(church_id,id),FOREIGN KEY(church_id,author_id) REFERENCES app_user(church_id,id),FOREIGN KEY(church_id,role_id) REFERENCES role(church_id,id));
CREATE FUNCTION protect_care_note() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='UPDATE' AND OLD.expires_at<=now() AND NEW.ciphertext IS NULL AND NEW.purged_at IS NOT NULL AND OLD.purged_at IS NULL AND (to_jsonb(NEW)-'ciphertext'-'purged_at')=(to_jsonb(OLD)-'ciphertext'-'purged_at') THEN RETURN NEW; END IF;
 RAISE EXCEPTION 'Notes are append-only except expired ciphertext purge' USING ERRCODE='23514'; END $$;
CREATE TRIGGER care_note_immutable BEFORE UPDATE OR DELETE ON care_note FOR EACH ROW EXECUTE FUNCTION protect_care_note();
CREATE INDEX care_due_idx ON care_record(church_id,completed_at,follow_up_on);
CREATE INDEX care_note_expiry_idx ON care_note(expires_at);
INSERT INTO permission(code) VALUES ('care.read'),('care.write'),('care.notes'),('care.policy');
INSERT INTO role_permission(role_id,permission_code) SELECT role_id,p.code FROM role_permission r CROSS JOIN (VALUES ('care.read'),('care.write'),('care.notes'),('care.policy')) p(code) WHERE r.permission_code='identity.manage';
